name: Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v6
        with:
          publish: false
          prerelease: false
          config-name: draft-release.yaml
          commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
